# Generated by Django 5.2.14 on 2026-09-24 19:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('tier', models.CharField(choices=[('free', 'Free Evaluation'), ('starter', 'Starter Tier'), ('pro', 'Professional Tier'), ('enterprise', 'Enterprise Cloud')], default='starter', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=150)),
                ('service_type', models.CharField(default='api', max_length=50)),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'In Review'), ('approved', 'Approved for Deployment'), ('completed', 'Deployed & Completed'), ('rejected', 'Declined')], default='pending', max_length=30)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('service_type', models.CharField(choices=[('api', 'Web API / Microservice'), ('worker', 'Background Worker / Queue'), ('database', 'Managed Database / Storage'), ('frontend', 'Frontend SPA / Edge App')], default='api', max_length=30)),
                ('environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('prod', 'Production')], default='prod', max_length=20)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('deploying', 'Deploying / Upgrading'), ('degraded', 'Degraded Performance'), ('stopped', 'Stopped / Maintenance')], default='healthy', max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='myapp.clientaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('client', 'slug')},
            },
        ),
    ]
