# Generated by Django 5.2.14 on 2026-09-29 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_clientaccount_deploymentinquiry_projectservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_port', models.IntegerField(default=22)),
                ('ssh_user', models.CharField(default='root', max_length=50)),
                ('ssh_auth_type', models.CharField(default='key', max_length=20)),
                ('ssh_credential', models.TextField(blank=True, help_text='Encrypted SSH private key or password')),
                ('status', models.CharField(choices=[('pending', 'Pending Registration'), ('provisioning', 'Provisioning K3s & GitOps'), ('ready', 'Ready (Active Cluster Node)'), ('failed', 'Provisioning Failed'), ('offline', 'Node Offline')], default='pending', max_length=30)),
                ('k3s_version', models.CharField(default='v1.30.0+k3s1', max_length=50)),
                ('cpu_cores', models.IntegerField(default=2)),
                ('ram_mb', models.IntegerField(default=4096)),
                ('disk_gb', models.IntegerField(default=50)),
                ('cloudflare_tunnel_id', models.CharField(blank=True, max_length=100)),
                ('cloudflare_tunnel_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='myapp.clientaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagedAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('addon_type', models.CharField(choices=[('postgres', 'PostgreSQL 16 High-Performance DB'), ('redis', 'Redis 7 In-Memory Cache'), ('mysql', 'MySQL 8 Relational Database'), ('clickhouse', 'ClickHouse Analytical OLAP DB')], default='postgres', max_length=30)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('running', 'Running & Healthy'), ('backup_active', 'Running (Backups Active)'), ('stopped', 'Stopped')], default='provisioning', max_length=30)),
                ('allocated_storage_gb', models.IntegerField(default=10)),
                ('connection_uri', models.CharField(blank=True, max_length=500)),
                ('r2_backup_enabled', models.BooleanField(default=True)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='myapp.clientaccount')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='myapp.servernode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('git_repo_url', models.URLField()),
                ('git_branch', models.CharField(default='main', max_length=100)),
                ('build_type', models.CharField(choices=[('dockerfile', 'Dockerfile'), ('nixpacks', 'Nixpacks (Auto-Detect)'), ('python', 'Python / WSGI / ASGI'), ('nodejs', 'Node.js / Next.js'), ('go', 'Golang Static Binary')], default='dockerfile', max_length=30)),
                ('target_port', models.IntegerField(default=8000)),
                ('replicas', models.IntegerField(default=2)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('environment_variables', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Deployment'), ('building', 'Building & Scanning Image'), ('deploying', 'Deploying Rollout'), ('active', 'Active (Zero-Downtime)'), ('degraded', 'Degraded Performance'), ('rolled_back', 'Rolled Back to Stable')], default='pending', max_length=30)),
                ('current_image', models.CharField(blank=True, max_length=255)),
                ('argo_app_name', models.CharField(blank=True, max_length=150)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='myapp.clientaccount')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='myapp.servernode')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('client', 'slug')},
            },
        ),
    ]
