# Generated by Django 5.2.14 on 2026-09-29 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_servernode_managedaddon_applicationdeployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeployment',
            name='auto_deploy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='latest_commit_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='latest_commit_sha',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=40)),
                ('commit_message', models.CharField(blank=True, max_length=255)),
                ('sender', models.CharField(default='github', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('building', 'Building & Scanning'), ('deployed', 'Blue/Green Deployed'), ('failed', 'Failed / Rolled Back')], default='queued', max_length=30)),
                ('rollout_strategy', models.CharField(default='blueGreen', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.applicationdeployment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
