# Generated by Django 5.2.14 on 2026-09-29 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_applicationdeployment_auto_deploy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='subscription_status',
            field=models.CharField(default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='tier',
            field=models.CharField(choices=[('free', 'Free Evaluation'), ('starter', 'Starter Tier ($9/mo)'), ('growth', 'Growth Tier ($29/mo)'), ('pro', 'Professional Tier (Legacy Growth)'), ('team', 'Team / Agency Tier ($79/mo)'), ('enterprise', 'Enterprise Cloud')], default='starter', max_length=30),
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(default='paid', max_length=30)),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=500)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='myapp.clientaccount')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
